import os
import json
import re
import time
import logging
from typing import Optional, List, Dict, Any
from dotenv import load_dotenv
from openai import OpenAI, RateLimitError, APIError

load_dotenv()
logger = logging.getLogger(__name__)

# Specialized model assignments
# 1. Fast, structured extraction (course circulars, exam dates, syllabus topics, timetable parsing)
EXTRACTION_MODEL = os.getenv("GROQ_EXTRACTION_MODEL", "llama-3.3-70b-versatile")

# 2. Multi-constraint reasoning & scheduling (schedule optimization, priority reasoning, conflict resolution)
REASONING_MODEL = os.getenv("GROQ_REASONING_MODEL", "deepseek-r1-distill-llama-70b")

GROQ_BASE_URL = "https://api.groq.com/openai/v1"


def get_groq_api_key(custom_key: Optional[str] = None) -> Optional[str]:
    """Retrieve Groq API key from explicit param, environment, or .env file."""
    if custom_key and custom_key.strip():
        return custom_key.strip()
    return os.getenv("GROQ_API_KEY") or os.getenv("GROQ_KEY")


def get_groq_client(custom_key: Optional[str] = None) -> Optional[OpenAI]:
    """Initialize standard OpenAI client pointed at Groq's OpenAI-compatible base URL."""
    api_key = get_groq_api_key(custom_key)
    if not api_key:
        return None
    return OpenAI(base_url=GROQ_BASE_URL, api_key=api_key)


def clean_groq_json_response(raw_text: str) -> str:
    """
    Strips markdown code fences and leading reasoning traces (such as <think>...</think>
    generated by deepseek-r1 models) before extracting and returning the last valid JSON block.
    """
    if not raw_text:
        return ""

    text = raw_text.strip()

    # 1. Remove deepseek-r1 <think>...</think> blocks
    text = re.sub(r"(?is)<think>.*?</think>", "", text).strip()

    # 2. Strip markdown code block fences (```json ... ``` or ``` ...)
    if "```" in text:
        # Match fenced code blocks
        fenced_blocks = re.findall(r"```(?:json)?\s*([\s\S]*?)\s*```", text)
        if fenced_blocks:
            # Prefer the last fenced code block if multiple exist
            text = fenced_blocks[-1].strip()
        else:
            text = re.sub(r"^```(?:json)?\s*", "", text)
            text = re.sub(r"\s*```$", "", text).strip()

    # 3. Direct JSON parse test
    try:
        json.loads(text)
        return text
    except Exception:
        pass

    # 4. Extract the last valid JSON object or array block from reasoning prose
    last_brace = text.rfind("}")
    last_bracket = text.rfind("]")

    if last_brace != -1 and last_brace > last_bracket:
        # Balanced bracket scan backwards for object {...}
        depth = 0
        start_idx = -1
        for i in range(last_brace, -1, -1):
            if text[i] == "}":
                depth += 1
            elif text[i] == "{":
                depth -= 1
                if depth == 0:
                    start_idx = i
                    break
        if start_idx != -1:
            candidate = text[start_idx : last_brace + 1].strip()
            try:
                json.loads(candidate)
                return candidate
            except Exception:
                pass

    elif last_bracket != -1:
        # Balanced bracket scan backwards for array [...]
        depth = 0
        start_idx = -1
        for i in range(last_bracket, -1, -1):
            if text[i] == "]":
                depth += 1
            elif text[i] == "[":
                depth -= 1
                if depth == 0:
                    start_idx = i
                    break
        if start_idx != -1:
            candidate = text[start_idx : last_bracket + 1].strip()
            try:
                json.loads(candidate)
                return candidate
            except Exception:
                pass

    # Fallback to regex pattern match for outermost JSON block
    matches = list(re.finditer(r"(\{[\s\S]*\}|\[[\s\S]*\])", text))
    if matches:
        return matches[-1].group(0).strip()

    return text


def call_groq_chat(
    prompt: str,
    model: str = EXTRACTION_MODEL,
    temperature: float = 0.0,
    system_prompt: Optional[str] = None,
    custom_key: Optional[str] = None,
    max_retries: int = 1
) -> str:
    """
    Executes a chat completion call using the OpenAI SDK pointed at Groq.
    Includes basic retry handling for HTTP 429 rate limit responses.
    """
    client = get_groq_client(custom_key)
    if not client:
        raise ValueError("GROQ_API_KEY is not configured.")

    messages: List[Dict[str, str]] = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    attempt = 0
    while attempt <= max_retries:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature
            )
            content = response.choices[0].message.content or ""
            return content.strip()
        except RateLimitError as rle:
            attempt += 1
            if attempt <= max_retries:
                wait_seconds = 2.5
                logger.warning(
                    "Groq API 429 Rate Limit encountered. Waiting %s seconds before retry (%d/%d)...",
                    wait_seconds, attempt, max_retries
                )
                time.sleep(wait_seconds)
            else:
                logger.error("Groq API 429 Rate Limit exceeded after retries: %s", rle)
                raise
        except Exception as exc:
            if "model_decommissioned" in str(exc).lower() and model != EXTRACTION_MODEL:
                logger.warning("Groq model '%s' decommissioned. Falling back to '%s'.", model, EXTRACTION_MODEL)
                return call_groq_chat(
                    prompt=prompt,
                    model=EXTRACTION_MODEL,
                    temperature=temperature,
                    system_prompt=system_prompt,
                    custom_key=custom_key,
                    max_retries=0
                )
            logger.error("Groq API request failed with error: %s", exc)
            raise
